// <auto-generated />
using System;
using DataAccessLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLibrary.Migrations
{
    [DbContext(typeof(KieliodbContext))]
    [Migration("20260109031954_AddOrder")]
    partial class AddOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLibrary.Entities.Conjugation", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Oid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Form")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Form");

                    b.Property<Guid>("LinkMidMoodPerson")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LinkMidMoodTense")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LinkVerb")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Oid");

                    b.HasIndex("LinkMidMoodPerson");

                    b.HasIndex("LinkMidMoodTense");

                    b.HasIndex("LinkVerb");

                    b.ToTable("Conjugation", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.DeutschAdjektiv", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Oid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AdjectiveEnding")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("AdjectiveEnding");

                    b.Property<string>("ArticleEnding")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ArticleEnding");

                    b.Property<string>("Case")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Case");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Gender");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Type");

                    b.HasKey("Oid");

                    b.ToTable("DeutschAdjektiv", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.Language", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Oid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Name");

                    b.HasKey("Oid");

                    b.ToTable("Language", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.MidMoodPerson", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Oid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("LinkMood")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LinkVerbPerson")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoodType")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MoodType");

                    b.Property<string>("PersonType")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("PersonType");

                    b.HasKey("Oid");

                    b.HasIndex("LinkMood");

                    b.HasIndex("LinkVerbPerson");

                    b.ToTable("MidMoodPerson", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.MidMoodTense", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Oid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("LinkMood")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LinkTense")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoodType")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MoodType");

                    b.Property<string>("TenseName")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TenseName");

                    b.HasKey("Oid");

                    b.HasIndex("LinkMood");

                    b.HasIndex("LinkTense");

                    b.ToTable("MidMoodTense", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.Mood", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Oid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("LinkLanguage")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("Order");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Type");

                    b.HasKey("Oid");

                    b.HasIndex("LinkLanguage");

                    b.ToTable("Mood", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.Tense", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Oid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Description");

                    b.Property<Guid>("LinkLanguage")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("Order");

                    b.HasKey("Oid");

                    b.HasIndex("LinkLanguage");

                    b.ToTable("Tense", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.Verb", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Oid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Infinitive")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Infinitive");

                    b.Property<Guid>("LinkLanguage")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PastParticiple")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("PastParticiple");

                    b.Property<bool>("Reflexive")
                        .HasColumnType("bit")
                        .HasColumnName("Reflexive");

                    b.Property<bool>("Regular")
                        .HasColumnType("bit")
                        .HasColumnName("Regular");

                    b.Property<bool>("Separable")
                        .HasColumnType("bit")
                        .HasColumnName("Separable");

                    b.Property<string>("Translation")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Translation");

                    b.HasKey("Oid");

                    b.HasIndex("LinkLanguage");

                    b.ToTable("Verb", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.VerbPerson", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Oid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("LinkLanguage")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("Order");

                    b.Property<string>("Pronoun")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Pronoun");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Type");

                    b.HasKey("Oid");

                    b.HasIndex("LinkLanguage");

                    b.ToTable("VerbPerson", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.Conjugation", b =>
                {
                    b.HasOne("DataAccessLibrary.Entities.MidMoodPerson", "MidMoodPerson")
                        .WithMany("Conjugations")
                        .HasForeignKey("LinkMidMoodPerson")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccessLibrary.Entities.MidMoodTense", "MidMoodTense")
                        .WithMany("Conjugations")
                        .HasForeignKey("LinkMidMoodTense")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccessLibrary.Entities.Verb", "Verb")
                        .WithMany("Conjugations")
                        .HasForeignKey("LinkVerb")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MidMoodPerson");

                    b.Navigation("MidMoodTense");

                    b.Navigation("Verb");
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.MidMoodPerson", b =>
                {
                    b.HasOne("DataAccessLibrary.Entities.Mood", "Mood")
                        .WithMany("MidMoodPersons")
                        .HasForeignKey("LinkMood")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccessLibrary.Entities.VerbPerson", "VerbPerson")
                        .WithMany("MidMoodPersons")
                        .HasForeignKey("LinkVerbPerson")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Mood");

                    b.Navigation("VerbPerson");
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.MidMoodTense", b =>
                {
                    b.HasOne("DataAccessLibrary.Entities.Mood", "Mood")
                        .WithMany("MidMoodTenses")
                        .HasForeignKey("LinkMood")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccessLibrary.Entities.Tense", "Tense")
                        .WithMany("MidMoodTenses")
                        .HasForeignKey("LinkTense")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Mood");

                    b.Navigation("Tense");
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.Mood", b =>
                {
                    b.HasOne("DataAccessLibrary.Entities.Language", "Language")
                        .WithMany("Moods")
                        .HasForeignKey("LinkLanguage")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.Tense", b =>
                {
                    b.HasOne("DataAccessLibrary.Entities.Language", "Language")
                        .WithMany("Tenses")
                        .HasForeignKey("LinkLanguage")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.Verb", b =>
                {
                    b.HasOne("DataAccessLibrary.Entities.Language", "Language")
                        .WithMany("Verbs")
                        .HasForeignKey("LinkLanguage")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.VerbPerson", b =>
                {
                    b.HasOne("DataAccessLibrary.Entities.Language", "Language")
                        .WithMany("VerbPersons")
                        .HasForeignKey("LinkLanguage")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.Language", b =>
                {
                    b.Navigation("Moods");

                    b.Navigation("Tenses");

                    b.Navigation("VerbPersons");

                    b.Navigation("Verbs");
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.MidMoodPerson", b =>
                {
                    b.Navigation("Conjugations");
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.MidMoodTense", b =>
                {
                    b.Navigation("Conjugations");
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.Mood", b =>
                {
                    b.Navigation("MidMoodPersons");

                    b.Navigation("MidMoodTenses");
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.Tense", b =>
                {
                    b.Navigation("MidMoodTenses");
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.Verb", b =>
                {
                    b.Navigation("Conjugations");
                });

            modelBuilder.Entity("DataAccessLibrary.Entities.VerbPerson", b =>
                {
                    b.Navigation("MidMoodPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
